ProjetoEdicaoEndereco/Models/Individuo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SistemaAtulizarEndereco.Models
{
    public class Individuo
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Documento { get; set; }
        public DateTime DataNascimento { get; set; }
        public Carro Carro { get; set; }
        public IndividuoContato IndividuoContato { get; set; }
        public IndividuoEndereco IndividuoEndereco { get; set; }
    }
}

ProjetoEdicaoEndereco/Controllers/IndividuoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoEdicaoEndereco.Repositories;

namespace ProjetoEdicaoEndereco.Controllers
{
    public class IndividuoController : Controller
    {
        private readonly IIndividuoRepositorio _individuoRepositorio;

        public IndividuoController(IIndividuoRepositorio individuoRepositorio)
        {
            _individuoRepositorio = individuoRepositorio;
        }

        public IActionResult Detalhes()
        {
            if (HttpContext.Session.GetInt32("IndividuoId") == null)
            {
                return RedirectToAction("NotFound", "Login");
            }

            int individuoId = (int)HttpContext.Session.GetInt32("IndividuoId");

            var individuo = _individuoRepositorio.ObterPorId(individuoId);

            return View(individuo);
        }
    }
}

ProjetoEdicaoEndereco/Controllers/IndividuoEnderecosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoEdicaoEndereco.Data;
using ProjetoEdicaoEndereco.Repositories;
using SistemaAtulizarEndereco.Models;

namespace ProjetoEdicaoEndereco.Controllers
{
    public class IndividuoEnderecosController : Controller
    {
        private readonly ProjetoEdicaoEnderecoContext _context;
        private readonly IIndividuoRepositorio _individuoRepositorio;

        public IndividuoEnderecosController(IIndividuoRepositorio individuoRepositorio, ProjetoEdicaoEnderecoContext context)
        {
            _individuoRepositorio = individuoRepositorio;
            _context = context;
        }

        public IActionResult Editar(int id)
        {
            try
            {
                var endereco = _context
                    .IndividuoEndereco
                    .Include(e => e.Cidade)
                    .ThenInclude(c => c.Estado)
                    .FirstOrDefault(e => e.Id == id);


                if (endereco == null)
                {
                    return NotFound();
                }

                ViewBag.Estados = _context.Estado.ToList();

                ViewBag.Cidades = _context.Cidade
                        .Where(c => c.EstadosId == endereco.Cidade.EstadosId)
                        .ToList();

                return View(endereco);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Erro ao exibir página de edição de endereço: {ex.Message}");

                return RedirectToAction("NotFound", "Login");
            }
        }

        [HttpPost]
        public IActionResult Editar(IndividuoEndereco endereco)
        {
            try
            {
                _context.Entry(endereco).State = EntityState.Modified;
                _context.SaveChanges();

                Console.WriteLine("Endereço atualizado com sucesso!");
                return RedirectToAction("Detalhes", "Individuo", new { id = endereco.IndividuoId });
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Erro ao atualizar endereço: {ex.Message}");
                return RedirectToAction("NotFound", "Login");
            }
        }

    }
}

ProjetoEdicaoEndereco/Views/Individuo/Detalhes.cshtml
<div class="container mt-4">
    <h2 class="mb-4">Indivíduo</h2>

    <div class="card mt-2">
        <div class="card-header bg-primary text-white">
            <i class="fas fa-user"></i> Informações Pessoais
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">Nome:</dt>
                <dd class="col-sm-7">@Model.Nome</dd>

                <dt class="col-sm-3">Documento:</dt>
                <dd class="col-sm-7">@Model.Documento</dd>

                <dt class="col-sm-3">Data de Nascimento:</dt>
                <dd class="col-sm-7">@Model.DataNascimento.ToShortDateString()</dd>
            </dl>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-header bg-info text-white">
            <i class="fas fa-phone"></i> Contato
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">DDI:</dt>  
                <dd class="col-sm-7">@Model.IndividuoContato.Ddi</dd> 

                <dt class="col-sm-3">DDD:</dt> 
                <dd class="col-sm-7">@Model.IndividuoContato.Ddd</dd> 

                <dt class="col-sm-3">Telefone:</dt> 
                <dd class="col-sm-7">@Model.IndividuoContato.Telefone</dd> 

                <dt class="col-sm-3">WhatsApp:</dt> 
                <dd class="col-sm-7">@(Model.IndividuoContato.Whatsapp)</dd> 

                <dt class="col-sm-3">Tipo de Contato:</dt> 
                <dd class="col-sm-7">@Model.IndividuoContato.TipoContato</dd> 
            </dl>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-header bg-success text-white">
            <div class="row">
                <div class="col-6">
                    <i class="fas fa-map-marker-alt"></i> Endereço
                </div>
                <div class="col-6 d-flex justify-content-end">
                    <a asp-controller="IndividuoEnderecos" asp-action="Editar" asp-route-id="@Model.IndividuoEndereco.Id" class="btn btn-primary">Editar</a>
                </div>
            </div>
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">CEP:</dt>
                <dd class="col-sm-7">@Model.IndividuoEndereco.Cep</dd> 

                <dt class="col-sm-3">Logradouro:</dt> 
                <dd class="col-sm-7">@Model.IndividuoEndereco.Logradouro</dd> 

                <dt class="col-sm-3">Bairro:</dt> 
                <dd class="col-sm-7">@Model.IndividuoEndereco.Bairro</dd> 

                <dt class="col-sm-3">Número:</dt> 
                <dd class="col-sm-7">@Model.IndividuoEndereco.Numero</dd> 

                <dt class="col-sm-3">Complemento:</dt> 
                <dd class="col-sm-7">@Model.IndividuoEndereco.Complemento</dd> 

                <dt class="col-sm-3">Estado:</dt> 
                <dd class="col-sm-7">@Model.IndividuoEndereco.Estado.Nome - @Model.IndividuoEndereco.Estado.Uf</dd>

                <dt class="col-sm-3">Cidade:</dt>
                <dd class="col-sm-7">@Model.IndividuoEndereco.Cidade.Nome - @Model.IndividuoEndereco.Cidade.Uf</dd>
            </dl>
        </div>
    </div>

    <div class="card mt-2">
        <div class="card-header bg-warning text-dark">
            <i class="fas fa-car"></i> Carro
        </div>
        <div class="card-body">
            <dl class="row">
                <dt class="col-sm-3">Placa:</dt>
                <dd class="col-sm-7">@Model.Carro.Placa</dd>

                <dt class="col-sm-3">Categoria:</dt>
                <dd class="col-sm-7">@Model.Carro.Categoria</dd>

                <dt class="col-sm-3">Modelo:</dt>
                <dd class="col-sm-7">@Model.Carro.Modelo</dd>

                <dt class="col-sm-3">Ano:</dt>
                <dd class="col-sm-7">@Model.Carro.Ano</dd>
            </dl>
        </div>
    </div>

</div>